# Generated by Django 5.0.1 on 2024-06-13 12:26

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0004_alter_agreement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('WS', 'Wholesale'), ('RL', 'Retail'), ('PT', 'Post operator'), ('CT', 'Consignment')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('PI', 'Purchase invoice'), ('SI', 'Sales invoice'), ('CN', 'Credit note'), ('DN', 'Debit note')], max_length=12)),
                ('time', models.DateTimeField()),
                ('number', models.CharField(max_length=50)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='counterparties.agreement')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='counterparties.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('outer_id', models.CharField(max_length=50)),
                ('uktzed', models.CharField(max_length=50)),
                ('vat_rate', models.CharField(choices=[('20%', 'Basic'), ('7%', 'Reduced'), ('0%', 'Export'), ('w/VAT', 'VAT free'), ('not VAT', 'Is not object for VAT')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
                ('basic_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.uom')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.CharField(choices=[('20%', 'Basic'), ('7%', 'Reduced'), ('0%', 'Export'), ('w/VAT', 'VAT free'), ('not VAT', 'Is not object for VAT')], max_length=12)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='stock.good')),
            ],
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.good')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='stock.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GoodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('time', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('RT', 'Receipt'), ('IS', 'Issue'), ('CN', 'Credit note'), ('DN', 'Debit note'), ('WO', 'Write off'), ('MG', 'Moving goods')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stock.document')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='stock.stockcard')),
            ],
        ),
    ]
