# Generated by Django 5.0.1 on 2024-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentline',
            name='vat_rate',
            field=models.CharField(choices=[('20%', '20%'), ('7%', '7%'), ('0%', '0%'), ('w/VAT', 'без ПДВ'), ('not VAT', 'не ПДВ')], max_length=12),
        ),
        migrations.AlterField(
            model_name='good',
            name='outer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='uktzed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='vat_rate',
            field=models.CharField(choices=[('20%', '20%'), ('7%', '7%'), ('0%', '0%'), ('w/VAT', 'без ПДВ'), ('not VAT', 'не ПДВ')], max_length=12),
        ),
    ]
