# Generated by Django 5.0.1 on 2024-06-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_documentline_vat_rate_alter_good_outer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtransaction',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='stock.good'),
        ),
        migrations.AlterField(
            model_name='documentline',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_goods', to='stock.good'),
        ),
    ]
