# Generated by Django 5.0.1 on 2024-06-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_documentline_document_alter_goodtransaction_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.document'),
        ),
        migrations.AlterField(
            model_name='documentline',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.good'),
        ),
    ]
