# Generated by Django 5.0.1 on 2024-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockcard_cost_alter_documentline_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
