# Generated by Django 5.0.1 on 2024-06-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockcard_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.warehouse'),
        ),
    ]
