# Generated by Django 5.0.1 on 2024-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_documentline_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
