# Generated by Django 5.0.1 on 2024-06-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_document_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodtransaction',
            name='time',
        ),
    ]
