# Generated by Django 5.0.1 on 2024-06-17 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_goodtransaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcard',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 14, 26, 47, 380778)),
        ),
    ]
