# Generated by Django 5.0.1 on 2024-07-09 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_document_posted_alter_goodtransaction_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtransaction',
            name='document_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.documentline'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 16, 47, 31, 9755)),
        ),
    ]
