# Generated by Django 5.0.1 on 2024-07-09 13:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_goodtransaction_document_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtransaction',
            name='document_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.documentline'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 16, 50, 13, 425888)),
        ),
    ]
