# Generated by Django 5.0.1 on 2024-04-22 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('short_name', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('commencement_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('payment_delay_days', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('type', models.CharField(choices=[('VR', 'Vendor'), ('CR', 'Customer'), ('BK', 'Bank'), ('CN', 'Commissioner'), ('OR', 'Other')], max_length=32)),
                ('description', models.TextField()),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='counterparties.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('short_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='counterparties.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('short_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VR', 'Vendor'), ('CR', 'Customer'), ('BK', 'Bank'), ('CN', 'Commissioner'), ('OR', 'Other')], max_length=32)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='counterparties.contactperson')),
            ],
        ),
    ]
