# Generated by Django 5.0.1 on 2024-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_agreement_contactperson_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('CP', 'City phone'), ('MP', 'Mobile phone'), ('EM', 'e-mail'), ('AS', 'Address'), ('SN', 'Social network'), ('OR', 'Other')], max_length=32),
        ),
    ]
