# Generated by Django 5.0.1 on 2024-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
